const BAD_REQUEST_CODE = 400;
const SUCCESS_CODE = 200;
const CREATED_CODE = 201;
const SERVER_ERROR_CODE = 500;
module.exports = {
  BAD_REQUEST_CODE,
  SUCCESS_CODE,
  CREATED_CODE,
  SERVER_ERROR_CODE,
};
